// subcategoryOptions.js
const subcategoryOptionsDataOrignale = {
  "Apparel & Accessories": [
    "Men's Clothing",
    "Women's Clothing",
    "Footwear",
    "Bags & Backpacks",
    "Eyewear",
    "Hats & Caps",
    "Belts",
    "Scarves & Shawls",
    "Gloves & Mittens",
    "Socks & Hosiery",
    "Jewelry",
    "Watches",
    "Wallets & Cardholders",
    "Ties & Bowties",
    "Umbrellas",
    "Handkerchiefs",
    "Headbands & Hair Accessories",
    "Braces & Suspenders",
    "Aprons",
    "Patches & Pins",
    "Bandanas",
    "Masks & Face Coverings",
    "Costumes",
  ],
  Electronics: [
    "Consumer Electronics",
    "Home Appliances",
    "Computers and Accessories",
    "Mobile Devices",
    "Audio Equipment",
    "Video Equipment",
    "Gaming Devices",
    "Wearable Technology",
    "Communication Devices",
    "Photography Equipment",
    "Automotive Electronics",
    "Industrial Electronics",
    "Medical Electronics",
    "Test and Measurement Equipment",
    "Robotics",
    "Internet of Things (IoT) Devices",
    "Power Electronics",
    "Embedded Systems",
    "Semiconductor Devices",
    "Other Electronic Components",
  ],
  "Home & Garden": [
    "Home Decor",
    "Gardening",
    "DIY & Crafts",
    "Home Improvement",
    "Cleaning & Organization",
    "Outdoor Living",
    "Home Appliances",
    "Kitchen & Dining",
    "Bedding & Bath",
    "Furniture",
    "Pet Supplies",
    "Smart Home",
    "Seasonal Decor",
    "Storage & Organization",
  ],
  "Health & Beauty": [
    "Skincare",
    "Haircare",
    "Makeup",
    "Fragrances",
    "Personal Care",
    "Supplements",
    "Fitness",
    "Nutrition",
    "Wellness",
    "Dental Care",
    "Hygiene Products",
    "Cosmetics",
    "Grooming",
    "Weight Management",
    "Spa & Relaxation",
    "Nail Care",
    "Eye Care",
    "Healthy Living",
    "Aromatherapy",
    "Herbal Remedies",
    "Medical Devices",
    "First Aid",
    "Healthy Eating",
    "Self-care Products",
    "Skin Treatments",
    "Hair Treatments",
    "Body Treatments",
    "Natural Remedies",
    "Massage Therapy",
    "Yoga & Meditation",
    "Home Fitness Equipment",
    "Mindfulness",
    "Alternative Medicine",
  ],
  "Toys & Games": [
    "Action Figures",
    "Board Games",
    "Building Toys",
    "Dolls & Accessories",
    "Educational Toys",
    "Electronic Toys",
    "Outdoor Toys",
    "Puzzles",
    "Remote Control Toys",
    "Soft Toys",
    "Toy Vehicles",
    "Video Games",
  ],
  "Books & Media": [
    "Books",
    "Magazines",
    "Newspapers",
    "E-books",
    "Audiobooks",
    "Comics",
    "Graphic Novels",
    "Movies",
    "TV Shows",
    "Music",
    "Podcasts",
    "Documentaries",
    "Games",
    "Educational Materials",
    "Artwork",
  ],
  "Sports & Outdoors": [
    "Outdoor Recreation",
    "Team Sports",
    "Individual Sports",
    "Fitness & Exercise",
    "Camping & Hiking",
    "Cycling",
    "Water Sports",
    "Winter Sports",
    "Hunting & Fishing",
    "Golf",
    "Athletic Clothing",
    "Footwear",
    "Accessories",
    "Fan Shop",
  ],
  Automotive: [
    "Cars",
    "Trucks",
    "Motorcycles",
    "Commercial Vehicles",
    "Electric Vehicles",
    "Hybrid Vehicles",
    "Classic Cars",
    "Sports Cars",
    "Luxury Cars",
    "SUVs",
    "Vans",
    "Off-road Vehicles",
    "Car Accessories",
    "Car Parts",
    "Car Care Products",
    "Car Electronics",
    "Car Audio Systems",
    "Car Navigation Systems",
    "Car Maintenance",
    "Car Repair Services",
    "Auto Insurance",
    "Auto Financing",
    "Auto Leasing",
    "Auto Dealerships",
    "Car Rental Services",
    "Auto Auctions",
    "Automotive Events",
    "Automotive News",
    "Automotive Blogs",
  ],
  "Baby & Kids": [
    "Clothing",
    "Shoes",
    "Accessories",
    "Toys",
    "Books",
    "School Supplies",
    "Furniture",
    "Bedding",
    "Diapers & Potty Training",
    "Feeding Supplies",
    "Health & Safety",
    "Baby Gear",
    "Gifts",
  ],
  "Food & Grocery": [
    "Fresh Produce",
    "Meat & Seafood",
    "Dairy & Eggs",
    "Bakery",
    "Frozen Foods",
    "Canned Goods",
    "Pantry Staples",
    "Snacks & Sweets",
    "Beverages",
    "Condiments & Sauces",
    "Spices & Seasonings",
    "Organic & Natural",
    "Specialty Foods",
    "International Foods",
    "Health Foods",
    "Baby Food & Formula",
    "Pet Food",
  ],
  "Pet Supplies": [
    "Dog Supplies",
    "Cat Supplies",
    "Fish Supplies",
    "Bird Supplies",
    "Small Animal Supplies",
    "Reptile Supplies",
    "Horse Supplies",
    "Farm Animal Supplies",
    "Pet Food",
    "Pet Treats",
    "Pet Toys",
    "Pet Beds",
    "Pet Carriers",
    "Pet Grooming Supplies",
    "Pet Health Supplies",
    "Pet Training Supplies",
    "Pet Clothing and Accessories",
    "Aquarium Supplies",
    "Terrarium Supplies",
    "Bird Cage Accessories",
    "Horse Tack and Equipment",
    "Pet Cleaning Supplies",
    "Pet Bowls and Feeders",
    "Pet Identification and Tracking Devices",
    "Pet Memorials and Urns",
    "Pet Travel Accessories",
    "Pet Cameras and Monitors",
    "Pet Enclosures and Fencing",
    "Pet Doors and Gates",
    "Pet Strollers and Car Seats",
    "Other Pet Accessories",
  ],
  "Office Supplies": [
    "Writing Instruments",
    "Paper Products",
    "Binders and Accessories",
    "Desk Organizers",
    "Filing Supplies",
    "Adhesives and Fasteners",
    "Calendars and Planners",
    "Presentation Supplies",
    "Labels and Label Makers",
    "Envelopes and Mailers",
    "Staplers and Punches",
    "Storage Boxes and Bins",
    "Desk Accessories",
    "Clipboards and Forms",
    "Tape and Dispensers",
    "Rubber Stamps and Ink",
    "Shipping and Packaging Supplies",
    "Art Supplies",
    "Presentation Boards",
    "Whiteboards and Accessories",
    "Safety and Security Supplies",
    "Office Furniture",
    "Electronics and Accessories",
    "Janitorial and Cleaning Supplies",
    "Breakroom Supplies",
    "Health and Wellness Products",
  ],
  "Jewelry & Watches": [
    "Rings",
    "Necklaces",
    "Earrings",
    "Bracelets",
    "Brooches",
    "Pendants",
    "Anklets",
    "Chains",
    "Cufflinks",
    "Wristwatches",
    "Pocket Watches",
    "Smartwatches",
    "Watch Bands",
    "Watch Winders",
    "Jewelry Boxes",
    "Jewelry Sets",
    "Body Jewelry",
    "Hair Jewelry",
    "Toe Rings",
    "Pins",
    "Charms",
    "Keychains",
    "Masonic Jewelry",
    "Medical Alert Jewelry",
    "Wedding & Engagement Rings",
    "Vintage & Antique Jewelry",
    "Custom & Handmade Jewelry",
    "Luxury Watches",
    "Fashion Watches",
    "Sports Watches",
    "Dress Watches",
    "Casual Watches",
    "Children's Watches",
    "Unisex Watches",
    "Women's Watches",
    "Men's Watches",
  ],
  "Crafts & DIY": [
    "Paper crafts",
    "Sewing & needlework",
    "Knitting & crocheting",
    "Woodworking",
    "Metalworking",
    "Jewelry making",
    "Painting & drawing",
    "Pottery & ceramics",
    "Scrapbooking",
    "Candle making",
    "Soap making",
    "Upcycling & repurposing",
    "Glass crafts",
    "DIY home decor",
    "DIY fashion",
    "DIY gifts",
    "DIY gardening",
    "DIY electronics",
    "DIY woodworking projects",
    "DIY art & sculpture",
  ],
  "Art & Collectibles": [
    "Paintings",
    "Sculptures",
    "Prints",
    "Photography",
    "Drawings",
    "Mixed Media",
    "Digital Art",
    "Antiques",
    "Coins & Currency",
    "Stamps",
    "Vintage Collectibles",
    "Memorabilia",
    "Fine Art",
    "Decorative Art",
    "Folk Art",
    "Ceramics",
    "Glass Art",
    "Textile Art",
    "Ethnographic & Indigenous Art",
    "Asian Art",
    "European Art",
    "American Art",
    "African Art",
    "Oceanian Art",
    "Middle Eastern Art",
    "Latin American Art",
  ],
  "Travel & Luggage": [
    "Luggage Sets",
    "Suitcases",
    "Carry-Ons",
    "Duffel Bags",
    "Backpacks",
    "Travel Accessories",
    "Travel Pillows",
    "Travel Organizers",
    "Toiletry Bags",
    "Passport Holders",
    "Travel Adapters",
    "Luggage Tags",
    "Garment Bags",
    "Travel Wallets",
    "Travel Bottles",
    "Compression Socks",
    "Travel Locks",
    "Travel Scale",
    "Travel Irons",
    "Travel Steamers",
    "Travel Umbrellas",
    "Travel Blankets",
    "Travel Towels",
    "RFID Blocking Products",
    "Packing Cubes",
    "Shoe Bags",
    "Electronics Organizers",
    "Wheeled Backpacks",
    "Kids' Luggage",
    "Pet Carriers",
    "Camera Bags",
    "Bicycle Travel Cases",
    "Hiking Backpacks",
    "Hydration Packs",
    "Travel Books",
    "Travel Apps",
    "Travel Insurance",
    "Travel Magazines",
  ],
  "Fitness & Wellness": [
    "Exercise",
    "Nutrition",
    "Mental Health",
    "Physical Health",
    "Weight Management",
    "Mindfulness",
    "Yoga",
    "Meditation",
    "Strength Training",
    "Cardiovascular Health",
    "Flexibility",
    "Stress Management",
    "Sleep Hygiene",
    "Holistic Health",
    "Functional Training",
    "Recovery Techniques",
    "Self-Care Practices",
    "Healthy Lifestyle Habits",
    "Body Image",
    "Wellness Coaching",
    "Group Fitness",
    "Personal Training",
    "Health Education",
    "Wellness Retreats",
    "Mind-Body Connection",
    "Fitness Technology",
    "Athletic Performance",
    "Physical Therapy",
    "Alternative Medicine",
    "Hydration",
    "Healthy Eating Habits",
    "Preventive Health",
    "Resilience Building",
    "Relaxation Techniques",
    "Energy Management",
    "Disease Prevention",
    "Wellness Programs",
    "Rehabilitation",
    "Corporate Wellness",
    "Community Fitness",
    "Outdoor Activities",
    "Sports Medicine",
  ],
  "Home Improvement": [
    "Interior Design",
    "DIY Projects",
    "Home Renovation",
    "Kitchen Remodeling",
    "Bathroom Renovation",
    "Flooring",
    "Painting",
    "Furniture Restoration",
    "Organization & Storage Solutions",
    "Landscaping",
    "Outdoor Living Spaces",
    "Energy Efficiency Improvements",
    "Smart Home Technology Integration",
    "Home Maintenance",
    "Appliance Upgrades",
    "Window Treatments",
    "Lighting Design",
    "Wallpapering",
    "HVAC (Heating, Ventilation, and Air Conditioning)",
    "Plumbing",
    "Electrical Wiring",
    "Carpentry",
    "Roofing",
    "Siding",
    "Deck Construction",
    "Fencing",
    "Insulation",
    "Garage Organization",
    "Basement Finishing",
    "Attic Conversion",
    "Home Security Systems",
    "Fireplace Installation/Remodeling",
    "Patio and Porch Design",
    "Garden Design",
    "Waterproofing",
  ],
  "Electronics Accessories": [
    "Cables and Adapters",
    "Chargers and Power Banks",
    "Cases and Covers",
    "Screen Protectors",
    "Styluses",
    "Headphone and Earphone Accessories",
    "Mounts and Stands",
    "Memory Cards and USB Drives",
    "Cleaning Kits",
    "Docking Stations",
    "Gaming Accessories",
    "Smartwatch Accessories",
    "Camera Accessories",
    "Bluetooth Accessories",
    "Replacement Parts",
    "Protective Films",
    "Remote Controls",
    "Keyboards and Mice",
    "Car Accessories",
    "Travel Accessories",
    "Security Devices",
    "Cables Management",
    "Battery Accessories",
    "Audio and Video Splitters",
    "Repair Tools",
  ],
  "Gifts & Occasions": [
    "Birthday",
    "Anniversary",
    "Wedding",
    "Graduation",
    "Baby Shower",
    "Housewarming",
    "Christmas",
    "Valentine's Day",
    "Mother's Day",
    "Father's Day",
    "Easter",
    "Halloween",
    "Thanksgiving",
    "New Year's",
    "Retirement",
    "Promotion",
    "Engagement",
    "Bridal Shower",
    "Bachelor/Bachelorette Party",
    "Get Well Soon",
    "Sympathy",
    "Apology",
    "Congratulations",
    "Farewell",
    "Just Because",
  ],
  "Music & Instruments": [
    "Instruments",
    "Musical Theory",
    "Sheet Music",
    "Music Production",
    "Music History",
    "Music Technology",
    "Music Education",
    "Music Therapy",
  ],
  "Party Supplies": [
    "Balloons",
    "Streamers",
    "Tableware",
    "Decorations",
    "Party favors",
    "Invitations",
    "Pinatas",
    "Party hats",
    "Confetti",
    "Party games",
    "Costumes",
    "Cake toppers",
    "Candles",
    "Party lights",
    "Themed decorations",
    "Disposable plates and cups",
    "Party bags",
    "Photo booth props",
    "Table covers",
    "Napkins",
    "Cutlery",
    "Drinkware",
    "Table centerpieces",
    "Banners",
    "Backdrops",
    "Party favors",
    "Gift bags",
    "Ribbons",
    "Serving trays",
    "Ice buckets",
    "Drink dispensers",
    "Food trays",
    "Table skirts",
    "Chair covers",
    "Tissue paper pom-poms",
    "Streamer backdrops",
    "Photo backdrops",
    "Party hats",
    "Party masks",
    "Noise makers",
    "Sashes",
    "Wristbands",
    "Photo frames",
    "Props",
  ],

  Services: [
    "Cleaning Services",
    "Maintenance Services",
    "Consulting Services",
    "Legal Services",
    "Financial Services",
    "Healthcare Services",
    "Education Services",
    "Transportation Services",
    "Hospitality Services",
    "Information Technology Services",
    "Marketing Services",
    "Entertainment Services",
    "Event Planning Services",
    "Security Services",
    "Insurance Services",
    "Real Estate Services",
    "Travel Services",
    "Human Resources Services",
    "Delivery Services",
    "Fitness Services",
  ],
};

export default subcategoryOptionsDataOrignale;
