const subcategoryOptionsData = {
  "Apparel & Accessories": [
    "Men's Clothing",
    "Women's Clothing",
    "Shoes",
    "Accessories",
    "Jewelry",
    "Bags",
    "Watches",
  ],
  Electronics: [
    "Computers",
    "Smartphones",
    "Tablets",
    "Cameras",
    "Headphones",
    "Gaming Consoles",
    "Printers & Scanners",
  ],
  "Home & Garden": [
    "Furniture",
    "Kitchenware",
    "Bedding",
    "Home Decor",
    "Gardening Supplies",
    "Tools",
    "Storage & Organization",
  ],
  "Health & Beauty": [
    "Skincare",
    "Haircare",
    "Makeup",
    "Personal Care",
    "Vitamins & Supplements",
    "Fragrances",
    "Wellness",
  ],
  "Toys & Games": [
    "Action Figures",
    "Board Games",
    "Dolls & Accessories",
    "Educational Toys",
    "Outdoor Play",
    "Puzzles",
    "Video Games",
  ],
  "Books & Media": [
    "Books",
    "Ebooks",
    "Movies",
    "Music",
    "Magazines",
    "Newspapers",
    "Podcasts",
  ],
  "Baby & Kids": [
    "Baby Gear",
    "Toys",
    "Kids' Clothing",
    "Kids' Shoes",
    "Diapers & Wipes",
    "Feeding Essentials",
    "Nursery Furniture",
  ],
  "Office Supplies": [
    "Stationery",
    "Office Furniture",
    "Writing Instruments",
    "Office Electronics",
    "Desk Accessories",
    "Organization",
    "Calendars & Planners",
  ],
  "Travel & Luggage": [
    "Luggage",
    "Travel Accessories",
    "Backpacks",
    "Travel Electronics",
    "Travel Gear",
    "Packing Organizers",
    "Toiletry Kits",
  ],
  "Fitness & Wellness": [
    "Exercise Equipment",
    "Yoga & Pilates",
    "Fitness Apparel",
    "Supplements",
    "Sports Nutrition",
    "Fitness Trackers",
    "Gym Accessories",
  ],
  "Home Improvement": [
    "Tools",
    "Building Materials",
    "Paint & Supplies",
    "Electrical",
    "Plumbing",
    "Hardware",
    "Home Renovation",
  ],
  "Electronics Accessories": [
    "Cables & Adapters",
    "Cases & Covers",
    "Screen Protectors",
    "Chargers & Power Adapters",
    "Memory Cards",
    "Batteries",
    "Mounts & Stands",
  ],
  "Music & Instruments": [
    "Guitars",
    "Keyboards & Pianos",
    "Drums & Percussion",
    "Sheet Music",
    "DJ Equipment",
    "Microphones",
    "Music Accessories",
  ],
};

export default subcategoryOptionsData;
